namespace: mattermost-enterprise

stack:
  defines: process-group
  runnable-list:
    - mattermost-enterprise/database
    - mattermost-enterprise/mattermost
    - mattermost-enterprise/nginx
  variables:
    defines: variables
    db-user:
      type: string
      value: "mattermost"
    db-password:
      type: string
      value: "mattermost_password"   
    db-name:
      type: string
      value: "mattermost"
    nginx-listen-port:
      type: int
      value: 8080
    nginx-server-name:
      type: string
      value: mm.example.com
    TZ:
      env: TZ
      type: string
      value: "UTC"
    mattermost-server-name:
      type: string
      value: https://mm.example.com
    MATTERMOST_IMAGE_TAG:
      type: string
      value: "6.3"
    nginx-image-tag: 
       type: string
       value: "latest"
    mattermost-image-tag: 
       type: string
       value: "latest"       
